/**
 * Slovar izrazov. `re` je vzorec za samodejno označevanje prve pojavitve izraza na strani (rehype-izrazi):
 * pregibne oblike so zajete s končnicami \p{L}*, kratice se iščejo z velikimi črkami (cs: true).
 * `def` je kratka razlaga (oblaček ob izrazu), `more` dodatek na strani slovarja.
 * Razlage so poenostavljene po osnutku NPS 2050 (Preglednica 1 in besedilo) in EPBD (Direktiva (EU) 2024/1275, člen 2).
 */
export interface Izraz { id: string; term: string; abbr?: string; re: string; cs?: boolean; def: string; more?: string }

export const izrazi: Izraz[] = [
  { id: 'brezemisijska-stavba', term: 'brezemisijska stavba', abbr: 'ZEB', re: 'brezemisijsk\\p{L}* stav\\p{L}*',
    def: 'Stavba z zelo majhno rabo energije, ki je v celoti pokrita z energijo iz obnovljivih virov, brez emisij iz fosilnih goriv na mestu stavbe.',
    more: 'Opredeljena je v členu 2 EPBD. Vse nove stavbe morajo biti brezemisijske od leta 2030 (javne od leta 2028), ves stavbni fond pa do leta 2050. Na lestvici NPS 2050 je raven brezemisijske stavbe meja med razredoma A in B.' },
  { id: 'skoraj-nicenergijska-stavba', term: 'skoraj ničenergijska stavba', abbr: 'sNES', re: 'skoraj ničenergijsk\\p{L}* stav\\p{L}*',
    def: 'Stavba z zelo visoko energijsko učinkovitostjo, katere majhne potrebe po energiji so v veliki meri pokrite iz obnovljivih virov. Zahteva za nove stavbe od leta 2021.' },
  { id: 'celovita-prenova', term: 'celovita energetska prenova', re: 'celovit\\p{L}* (?:energetsk\\p{L}* )?prenov\\p{L}*',
    def: 'Prenova ovoja stavbe in tehničnih sistemov, po kateri stavba doseže zelo visoko energijsko učinkovitost – do leta 2030 raven skoraj ničenergijske, nato brezemisijske stavbe.',
    more: 'Lahko se izvede naenkrat ali v več korakih po izkazu o prenovi stavbe (postopna celovita prenova). V modelu NPS 2050 je ciljna raven celovite prenove razred B1.' },
  { id: 'izkaz-o-prenovi', term: 'izkaz o prenovi stavbe', re: 'izkaz\\p{L}* o prenovi',
    def: 'Načrt korakov prenove za posamezno stavbo, ki pove, katere ukrepe in v kakšnem vrstnem redu izvesti, da stavba postopno postane brezemisijska.' },
  { id: 'energetska-izkaznica', term: 'energetska izkaznica', abbr: 'EI', re: 'energetsk\\p{L}* izkaznic\\p{L}*',
    def: 'Dokument, ki pokaže energijsko učinkovitost stavbe: rabo energije, energijski razred in priporočila za izboljšave. Obvezna je pri prodaji in oddaji stavbe ali stanovanja.' },
  { id: 'energijski-razred', term: 'energijski razred', re: 'energijsk\\p{L}* razred\\p{L}*',
    def: 'Oznaka od A do G, ki pove, koliko primarne energije stavba porabi na kvadratni meter na leto. A je najboljši, v razredu G je 15 % najslabših stavb posamezne vrste.',
    more: 'Meje razredov so v NPS 2050 določene posebej za vsako vrsto stavb in se preverjajo najmanj vsakih pet let.' },
  { id: 'primarna-energija', term: 'primarna energija', re: 'primarn\\p{L}* energij\\p{L}*',
    def: 'Energija iz naravnih virov pred pretvorbo. Upošteva tudi energijo, porabljeno in izgubljeno pri proizvodnji in prenosu elektrike in toplote. Na njej temeljijo energijski razredi.' },
  { id: 'koncna-energija', term: 'končna energija', re: 'končn\\p{L}* energij\\p{L}*',
    def: 'Energija, ki jo stavba prejme in porabi: elektrika, zemeljski plin, kurilno olje, les, daljinska toplota.' },
  { id: 'faktor-primarne-energije', term: 'faktor primarne energije', re: 'faktor\\p{L}* (?:skupne )?primarne energije',
    def: 'Število, ki pove, koliko primarne energije je potrebne za eno enoto dobavljene končne energije. Pri elektriki se zmanjšuje, ko raste delež obnovljivih virov.' },
  { id: 'kwh-m2', term: 'kWh/(m²·a)', re: 'kWh/\\(m²·a\\)', cs: true,
    def: 'Kilovatne ure na kvadratni meter uporabne površine na leto. Enota za primerjavo rabe energije stavb različnih velikosti.' },
  { id: 'ktoe', term: 'ktoe', re: 'ktoe', cs: true,
    def: 'Tisoč ton ekvivalenta nafte, enota za velike količine energije. 1 ktoe je približno 11,63 GWh.' },
  { id: 'uporabna-povrsina', term: 'uporabna površina', re: 'uporabn\\p{L}* površin\\p{L}*',
    def: 'Površina prostorov v stavbi po katastru nepremičnin, brez zunanjih zidov. Na njej temeljijo podatki o stavbnem fondu.' },
  { id: 'stopnja-prenove', term: 'stopnja prenove', re: 'stopnj\\p{L}* (?:energetske )?prenov\\p{L}*',
    def: 'Delež površine stavb, ki se v enem letu energetsko prenovi. NPS 2050 predvideva okoli 2 % na leto.' },
  { id: 'trajektorija', term: 'trajektorija', re: 'trajektorij\\p{L}*',
    def: 'Pot zmanjševanja povprečne rabe primarne energije vseh stanovanjskih stavb od leta 2020 do 2050 z vmesnimi mejniki, kot jo zahteva člen 9(2) EPBD.' },
  { id: 'najmanj-ucinkovite', term: '43 % energetsko najmanj učinkovitih stavb', re: '43 % (?:energetsko |energijsko )?najmanj učinkovit\\p{L}*',
    def: 'Skupina stanovanjskih stavb z najvišjo rabo primarne energije, ki obsega 43 % površine stanovanjskega fonda. Iz njihove prenove mora priti najmanj 55 % zmanjšanja rabe energije stanovanjskih stavb.' },
  { id: 'minimalni-standardi', term: 'minimalni standardi energetske učinkovitosti', abbr: 'MEPS', re: 'minimaln\\p{L}* (?:energetsk\\p{L}* )?standard\\p{L}*|MEPS',
    def: 'Obvezni pragovi za nestanovanjske stavbe (člen 9(1) EPBD): do leta 2030 morajo biti izboljšane vse stavbe med 16 % energetsko najslabših, do leta 2033 pa vse med 26 % najslabših.' },
  { id: 'epbd', term: 'EPBD', re: 'EPBD', cs: true,
    def: 'Evropska direktiva o energetski učinkovitosti stavb (Direktiva (EU) 2024/1275). Zahteva, da vsaka država članica pripravi nacionalni načrt prenove stavb.' },
  { id: 'nepn', term: 'NEPN 2024', re: 'NEPN(?: 2024)?', cs: true,
    def: 'Posodobljeni celoviti nacionalni energetski in podnebni načrt Slovenije iz leta 2024. Določa energetske in podnebne cilje države do leta 2030.' },
  { id: 'dseps', term: 'DSEPS 2050', re: 'DSEPS(?: 2050)?', cs: true,
    def: 'Dolgoročna strategija energetske prenove stavb do leta 2050 iz leta 2021. NPS 2050 jo nadgrajuje po zahtevah nove EPBD.' },
  { id: 'ove', term: 'obnovljivi viri energije', abbr: 'OVE', re: 'OVE', cs: true,
    def: 'Obnovljivi viri energije: sončna energija, les in druga biomasa, toplota okolja (toplotne črpalke), veter, voda.' },
  { id: 'ure', term: 'učinkovita raba energije', abbr: 'URE', re: 'URE', cs: true,
    def: 'Učinkovita raba energije: ukrepi, ki zmanjšajo rabo energije ob enakem udobju, na primer izolacija, nova okna, prezračevanje z vračanjem toplote.' },
  { id: 'tgp', term: 'toplogredni plini', abbr: 'TGP', re: 'toplogredn\\p{L}* plin\\p{L}*|TGP',
    def: 'Plini, ki povzročajo podnebne spremembe, predvsem ogljikov dioksid (CO₂). V stavbah nastajajo pri kurjenju fosilnih goriv in posredno pri proizvodnji elektrike in toplote.' },
  { id: 'gwp', term: 'emisije v življenjskem ciklu', abbr: 'GWP', re: 'GWP', cs: true,
    def: 'Potencial globalnega segrevanja v celotni življenjski dobi stavbe: od proizvodnje materialov in gradnje do rabe, rušenja in recikliranja.' },
  { id: 'ets2', term: 'ETS2', re: 'ETS2', cs: true,
    def: 'Evropski sistem trgovanja z emisijami za stavbe in promet. Dobavitelji goriv bodo morali kupovati emisijske kupone, del prihodkov pa se nameni ranljivim gospodinjstvom.' },
  { id: 'energetska-revscina', term: 'energetska revščina', re: 'energetsk\\p{L}* revščin\\p{L}*',
    def: 'Stanje, v katerem gospodinjstvo z nizkim dohodkom ne more zadovoljiti osnovnih potreb po energiji zaradi slabega stanovanja ali previsokih stroškov energije.' },
  { id: 'socialni-sklad', term: 'Socialni sklad za podnebje', re: 'Social\\p{L}* sklad\\p{L}* za podnebje',
    def: 'Evropski sklad za obdobje 2026–2032, ki ranljivim gospodinjstvom pomaga pri prehodu na čisto energijo. Slovenija ga črpa prek Socialnega načrta za podnebje.' },
  { id: 'eko-sklad', term: 'Eko sklad', re: 'Eko sklad\\p{L}*',
    def: 'Slovenski okoljski javni sklad. Dodeljuje nepovratne spodbude in ugodne kredite za energetsko prenovo in ogrevanje z obnovljivimi viri.' },
  { id: 'ensvet', term: 'ENSVET', re: 'ENSVET', cs: true,
    def: 'Mreža energetskih svetovalnih pisarn Eko sklada, ki občanom nudi brezplačno energetsko svetovanje.' },
  { id: 'vse-na-enem-mestu', term: 'točke »vse na enem mestu«', re: 'vse na enem mestu',
    def: 'Svetovalne točke, kjer bi lastniki na enem mestu dobili tehnično, upravno in finančno pomoč pri prenovi, od načrta do prijave na spodbude (predlog N18).' },
  { id: 'energetsko-pogodbenistvo', term: 'energetsko pogodbeništvo', re: 'energetsk\\p{L}* pogodbeništv\\p{L}*',
    def: 'Izvajalec prenovo financira in izvede, strošek pa se mu povrne iz doseženih prihrankov energije.' },
  { id: 'toplotna-crpalka', term: 'toplotna črpalka', re: 'toplotn\\p{L}* črpalk\\p{L}*',
    def: 'Naprava, ki za ogrevanje izkorišča toploto zraka, zemlje ali vode. Z eno enoto elektrike da tri do pet enot toplote.' },
  { id: 'kataster', term: 'kataster nepremičnin', re: 'katast(?:er|r\\p{L}+) nepremičnin',
    def: 'Uradna evidenca Geodetske uprave RS o stavbah in delih stavb. Iz nje so podatki o številu in površini stavb.' },
  { id: 'jrc', term: 'JRC', re: 'JRC', cs: true,
    def: 'Skupno raziskovalno središče Evropske komisije. Ocenilo je prvi osnutek načrta in predlagalo dopolnitve.' },
  { id: 'mzie', term: 'MzIE', re: 'MzIE', cs: true,
    def: 'Ministrstvo za infrastrukturo in energetiko, pripravljavec in nosilec NPS 2050.' },
];

/** Razvrščeno po abecedi za stran slovarja (slovenska kolacija). */
export const izraziAbc = [...izrazi].sort((a, b) => a.term.localeCompare(b.term, 'sl'));
